os: osx
language: node_js
node_js: 8.9.4
env:
  global:
  - NODE_ENV=test
  - OSENV=travis
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/Library/Caches/Homebrew"
  - node_modules
  - "$(npm config get prefix)/bin/gulp-cli"
  - "$(npm config get prefix)/bin/electron-packager"
before_install:
- openssl aes-256-cbc -K $encrypted_40ef2f4394e3_key -iv $encrypted_40ef2f4394e3_iv -in client-secret.json.enc -out client-secret.json -d
- brew install wine rpm
- npm i -g node-gyp
- npm i -g gulp-cli
- npm i -g electron-packager
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file client-secret.json
before_script:
- 'PACKAGE_VERSION=$(cat package.json  | grep version  | head -1  | awk -F: ''{ print $2 }''  | sed ''s/[",]//g''  | tr -d ''[[:space:]]'')'
- npm run make
script:
- npm run test
- if [ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "dev" ]; then zip -r out/selfkey-identity-wallet-darwin-x64-v$TRAVIS_BUILD_NUMBER.zip out/selfkey-identity-wallet-darwin-x64; fi
- if [ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "dev" ]; then gsutil cp out/selfkey-identity-wallet-darwin-x64-v$TRAVIS_BUILD_NUMBER.zip gs://selfkey-builds/$TRAVIS_BUILD_NUMBER/; fi
