os: osx
language: node_js
node_js: 9
env:
  global:
  - NODE_ENV=test
  - OSENV=travis
notifications:
  slack:
    secure: fZJNvR4gMUki9/UcaaXYf76JxsdvYV7X15wzkIdQU42qboFG8jvlEiKEr7WP4h3WShJEfG/l70YoSvzO+e3K7vJ+bdpNnvcvgChVZosqVLKmv/jipjmFEdYS11pVvaWPdTet04zmYqrB24waAsaeMt1hMUSAOSuFwvcoYd01fo2guzoGwc+2NkuZTRrGkn3jZ0muQGQNUfHNQGV9yNA1wgl354mi6Uaa0gb3VNev59RUYCsjBXb2+N14MZIAAZVvumm0jZxlX8KDQuwQDAc2GaHU8zC4SJ9rUxcvcfA8jN0dTk/X7RcuyTPGGy4OwL0ESPblBByJ0BUvcWosra4+Rzi+c3DNCTsTQmQdCoMSe0N2CmvhVi0XlGh1b5Efes8n9CIId2fVpw017Lh8J0C6YrRBtKWn3r1XWFOkwaAeQr7z89V3CnLxQdwu59IFyAdjSHcu1gIxKwP1Ad33zUTQlcZZpyswKk3DcEGVgZdRGlzPQ1i9w9PLYUiK+nVWRMY3+XYCnsQfSDYZI/1eLFMElaVTl4iWilAp1tUTWwAQOmlJzIX2ayuIxUrkbGmMu7smb7YjllVhef18yFB68y5SePOknYkeEYO5Sxa1KDCc+OsUlUIrnrmG7YSx6q1bKW7G74m0dj6ImR+goYDVNFZi28AsUD4xqFTA51uBQo/fqJY=
before_install:
- brew install wine rpm
- npm i -g gulp-cli
- npm i -g electron-packager
before_script:
- npm run make
deploy:
  provider: gcs
  #on:
  #  branch: travis-automated-deployment
  access_key_id: GOOGUYHHHUMEQ5GSNOWG
  secret_access_key:
    secure: i93rYCZtgyIBWO1PsLqqMfEIHP6swd56a+Nx8tdc8POBaxH2iIrJOPqnSijX9ScWudm81EFyl2Q3Fca9vxT47CA+tYj1JDnSyghz8MQdFrsP1IDmIjZAdqpOanKZRpAJ/AOYdD5yKJmtYzYQb97P9zYsuCic7JUAjGgnKAj0Qp6IT3pqMJ964rBAfas2XWIBtxAbBUCvU9kCNXk6DDjXxtd6kSxedfbYNeieIBhNIR+lQtRcj/kI/60YC66iGtgHPdX9c/aVi+N9K1zsNk2jBwLGPoDZwybV0Xjby+KJEUmtHAJ/KmkiMsv7fRQzTwLioRArYubWC2kI/st7xo9qyaR2VzLS+t3XqEYO2BQbiqQGlAyGDyJAqJD0d9IXGWpLAGomxO2qmRbU5q1+ox1C5gsAm5ICFyy+Z6TFzM2OQ7aEMzpzKkKvQwXX/9nYl2WvXHRO2P9cRmWweBybY6xILgYru/LoJheo5IsYd86b9STbCN6gvObkhym6X5WWbuv0y7HzhpDewZ2XXe+OG5biTX+dNV3+3Jyb0pTJWISwldgbL1Rn5KOEuFc5E0U60MlNzMNJxLfCZ1cF2B6dlpFVI/LJNQltLXUwU+fZAXDbs/nENxOz6IbHxvkoA4tZPg/13douujTD1sEmup2G2FITeQeQXz4tDkYqRemLKHqF7RU=
  bucket: selfkey-builds
  skip_cleanup: true
  #acl: public-read
  #local-dir: out


