os: osx
language: node_js
node_js: 9
cache: yarn
env:
  global:
  - OSENV=travis
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - npm i -g gulp-cli electron-packager
  - npm install --global yarn
before_script:
  - yarn dist
script:
  - yarn test
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    condition: $TRAVIS_PULL_REQUEST != false
