environment:
  nodejs_version: "9"
  NODE_ENV: production
  OSENV: windows
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g gulp-cli
  - npm i -g electron-packager
  - npm i --production=false
build_script:
  - npm run make-auto
test_script:
  - npm run test
after_test:
  - appveyor PushArtifact C:\projects\identity-wallet\out\selfkey-identity-wallet-win32-ia32\selfkey-identity-wallet.exe
  - appveyor PushArtifact C:\projects\identity-wallet\out\selfkey-identity-wallet-win32-ia32\Update.exe
