environment:
  nodejs_version: "9"
  NODE_ENV: production
  OSENV: windows
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g gulp-cli
  - npm i -g electron-packager
  - npm i --production=false
build_script:
  - npm run make-auto
after_build:
  - ps: Get-ChildItem -Path *.exe -Recurse
  - ps: Get-ChildItem -Path *.zip -Recurse
test_script:
  - npm run test
after_test:
  - appveyor PushArtifact out\id-wallet-win32-ia32\Identity-Wallet-Installer.exe
