version: 2

jobs:
  "build":
    docker: &DOCKERIMAGE
      - image: circleci/node:9.11.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Gulp
          command: sudo npm i -g gulp-cli
      - run:
          name: Install Node Packages
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Build App
          command: yarn dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  "e2e":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
            at: .
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: E2E Tests
          command: yarn test

  "stage":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Deploy to staging
          command: |
            if [[ -n ${CIRCLE_PR_NUMBER} ]]
            then
                bash ../deploy.sh
            fi      
workflows:
  version: 2
  workflow1:
    jobs:
      - "build"
      - "e2e":
        requires:
            - build
      - "stage":
          requires:
            - e2e


